const languages = {
  en: "English",
  ar: "العربية",
  ur: "اردو",
  hi: "हिन्दी",
  bn: "বাংলা",
  id: "Bahasa Indonesia",
  ms: "Bahasa Melayu",
  tr: "Türkçe",
  fa: "فارسی",
  fr: "Français",
  de: "Deutsch",
  es: "Español",
  it: "Italiano",
  pt: "Português",
  ru: "Русский",
  uk: "Українська",
  nl: "Nederlands",
  pl: "Polski",
  el: "Ελληνικά",
  ro: "Română",
  cs: "Čeština",
  sv: "Svenska",
  da: "Dansk",
  no: "Norsk",
  fi: "Suomi",
  ja: "日本語",
  ko: "한국어",
  zh: "中文",
  th: "ไทย",
  vi: "Tiếng Việt",
  sq: "Shqip"
};

window.languages = languages;
